version: '3.4'
services:
  web:
    image: docker-temp-repos.myket.ir/jewerly-shop:latest
    ports: 
      - '8000:8000'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
        order: start-first
